version: "3.8"

services:
  app:
    build: .
    container_name: nothing_better_than_al_api
    env_file: .env
    restart: unless-stopped
    entrypoint: docker-entrypoint.sh
    networks:
      - caddy
      - nothing_better_than_al_api

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'timezone=Europe/Paris'
    networks:
      - nothing_better_than_al_api

volumes:
  postgres-data:
    driver: local

networks:
  caddy:
    external: true
  nothing_better_than_al_api:
