version: "3.8"

services:
  nothing_better_than_al_api:
    build: .
    container_name: nothing_better_than_al_api
    entrypoint: ["./docker-entrypoint.sh"]
    env_file: .env
    restart: unless-stopped
    networks:
      - caddy
      - monitoring
      - nothing_better_than_al_api_network

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'timezone=Europe/Paris'
    networks:
      - nothing_better_than_al_api_network

volumes:
  postgres-data:
    driver: local

networks:
  caddy:
    external: true
  monitoring:
    external: true
  nothing_better_than_al_api_network:
