version: "3.8"

services:
  postgres-db:
    image: postgres:16.2-alpine3.19
    container_name: postgres-db
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'timezone=Europe/Paris'

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:
    driver: local
