version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    env_file: .env
    expose:
      - 5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c 'timezone=Europe/Paris'

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:
    driver: local
